[tox]
minversion = 2.9.0
skipdist = True
skip_missing_interpreters = true
envlist = ruff,py311
requires = tox-uv

isolated_build = true

[testenv]
description = Run unit-testing
setenv =
    _PYTEST_SETUP_SKIP_APRSD_DEP=1
    PYTHONDONTWRITEBYTECODE=1
    PYTHONUNBUFFERED=1
usedevelop = True
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev,tests]
    coverage: coverage
    pytestmain: git+https://github.com/pytest-dev/pytest.git@main
commands =
    pytest -v --cov-report term-missing --cov=aprsd_irc_extension {posargs}
    coverage: coverage report -m
    coverage: coverage xml

[testenv:docs]
skip_install = true
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
    {toxinidir}/.
changedir = {toxinidir}/docs
commands =
    {envpython} clean_docs.py
    sphinx-apidoc --force --output-dir apidoc {toxinidir}/aprsd_irc_extension
    sphinx-build -a -W . _build

[testenv:ruff]
skip_install = true
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
commands =
    ruff check {posargs} aprsd_irc_extension tests

[testenv:fast8]
basepython = python3.11
# Use same environment directory as ruff env to save space and install time
envdir = {toxworkdir}/ruff
commands =
  {toxinidir}/tools/fast8.sh
passenv = FAST8_NUM_COMMITS

[testenv:lint]
skip_install = true
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
commands =
    ruff check aprsd_irc_extension tests

# This is the configuration for the tox-gh-actions plugin for GitHub Actions
#   https://github.com/ymyzk/tox-gh-actions
# This section is not needed if not using GitHub Actions for CI.
[gh-actions]
python =
    3.11: py311, ruff, type-check, docs

[testenv:fmt]
# This will reformat your code using ruff
skip_install = true
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
commands =
    ruff format aprsd_irc_extension tests

[testenv:type-check]
skip_install = true
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
commands =
    mypy aprsd-irc

[testenv:pre-commit]
skip_install = true
basepython = python3.11
install_command = uv pip install {opts} {packages}
deps =
    -e {toxinidir}[dev]
commands = pre-commit run --all-files --show-diff-on-failure
